---
# Setup the playbook

- name: Configure basic packages and functionality
  hosts: all
  remote_user: vagrant
  roles:
   - base

- name: Setup and configure webserver
  hosts: webserver
  remote_user: vagrant
  roles:
    - webserver

- name: Setup MySQL database
  hosts: mysqlserver
  user: vagrant
  roles:
    - mysqlserver
  vars:
    username: root
    password: root
    database: blueberryh_dev

- name: Setup Elasticmq Message queueing system
  hosts: sqsserver
  user: vagrant
  roles:
    - sqsserver
  vars:
    wgeturl: https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-0.8.7.jar
