---
# Setup the playbook

- name: Configure basic packages and functionality
  hosts: all
  remote_user: vagrant
  roles:
   - base

- name: Setup and configure webserver
  hosts: webserver
  remote_user: vagrant
  roles:
    - webserver

- name: Setup MySQL database
  hosts: dbserver
  user: vagrant
  roles:
    - database
  vars:
    username: root
    password: root
    database: blueberryh_dev

- name: Setup Ruby and Ruby on Rails Development Env
  hosts: rubydev
  user: vagrant
  roles:
    - rubydev